### ISSUE TITLE
Latest version will not start up

### ISSUE THREAD

**Issue by RyanEwen** [adferrand/docker-backuppc#10]
When I try to run the latest version using the basic run command in the doc, there is an error about the rsync version, and the web UI shows errors about the backend not running.

Running 4.2.1 works fine, however.

**Comment by adferrand** [comment]
Indeed. Upstream broke rsync-bpc on latest version (3.0.9.13). I made a fallback on version 3.0.9.12, and pushed a new version of my docker with this bugfix: 4.3.0-2. All concerned tags (latest, 4, 4.3.0-1, 4.3.0) are also patched.

Really sorry for the inconvenience, I trusted blindly my unit tests, I will add integration tests to be blocked  by my CI on this kind of situation.
