### ISSUE TITLE
Getting 404

### ISSUE THREAD

**Issue by stranskj** [adferrand/docker-backuppc#16]
Hi,
when i run the container using the testing instructions, I am getting 404 error.
I have checked the lighttpd configuration, and there is not index (or any other HTML-like) file in /var/www/html/backuppc
I might be missing something, however.

**Comment by stranskj** [comment]
I have reproduced this with other mean of BackupPC installation, so it might not be related to the Docker image.

**Comment by adferrand** [comment]
Yes, you may be right, as I clearly remember that calling root context would lead to the administrative interface before in my container. Maybe one of the latest versions of BackupPC made a regression about that. I did not caught it because I usually target directly the administrative interface directly during my tests. 

I will investigate also tomorrow.

**Comment by stranskj** [comment]
Hmm, could be. The other test I made was the installation script from BackupPC wiki running in a Ubuntu docker container, e.g. also completely as root.

**Comment by adferrand** [comment]
Hello @stranskj, I tested the docker today. When you hit the root context, `/`, you get a `301 REDIRECT` HTTP response to `/BackupPC_Admin`, that my browser honors correctly and lead me to the administration page.

It seems that this is the behavior for a long time.

So maybe your browser is not following the HTTP redirection for some reason, or you use a `curl` command that does not support redirections.

**Comment by stranskj** [comment]
Hi @adferrand, it seems to be an error between keyboard and chair. I have tried on a different system today, and it works indeed. It is just that I was surprised, that the address is case sensitive! It is very inconsistent with normal address bar behavior. Also backuppc documentation is very unclear, what the actual page is, as with v3 it used to be just /backuppc (or it is just me again).
So, perhaps removing the case sensitivity, or forward from legacy address (optional?) would be great feature, if it can be done by just lighttpd configuration.
But thanks for checking anyway.
