### ISSUE TITLE
ARM deployment error

### ISSUE THREAD

**Issue by asitemade4u** [adferrand/docker-backuppc#17]
Hi,
Thank you for the docker container! However, I get this error when trying to deploy it on an ARM 64 machine:

`standard_init_linux.go:207: exec user process caused "exec format error"`

After searching on the Web, I have transformed the call into a bash script with a shebang, but the error remains:

`#!/bin/bash
docker run \
    --name backuppc \
    --publish 80:8881 \
    --volume /mnt/mo2/bkp/backuppc/etc:/etc/backuppc \
    --volume /mnt/mo2/bkp/backuppc/home:/home/backuppc \
    --volume /mnt/mo2/bkp/backuppc/data:/data/backuppc \
    adferrand/backuppc`

I have also taken care of giving the right access rights, as stated in your (excellent) documentation.
Is the image incompatible with the ARM platform?
Best,
Stephen

**Comment by Alveel** [comment]
Yes, this image is built for x86/64, I don't think there's one for ARM.

From [this blog post](https://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/):
> Here we run Docker on a Raspberry Pi. So the CPU architecture here is ARM rather than x86/x64 by Intel or AMD. Thus, Docker-based apps you use have to be packaged specifically for ARM architecture! Docker-based apps packaged for x86/x64 will not work and will result in an error such as: `FATA[0003] Error response from daemon: Cannot start container 0f0fa3f8e510e53908e6a459e817d600b9649e621e7dede974d6a65761ad39e5: exec format error`

**Comment by asitemade4u** [comment]
Here is the `lscpu` of the machine:

`
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):               6
On-line CPU(s) list:   0-5
Thread(s) per core:    1
Core(s) per socket:    3
Socket(s):             2
Model:                 4
CPU max MHz:           1512.0000
CPU min MHz:           408.0000
BogoMIPS:              48.00
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32
`

**Comment by asitemade4u** [comment]
Thanks for the response!
