### ISSUE TITLE
Project is missing a CHANGELOG.md

### ISSUE THREAD

**Issue by ambis** [adferrand/docker-backuppc#2]
I would love to see a [changelog](https://keepachangelog.com/) for this project.

It would make things like https://github.com/adferrand/docker-backuppc/issues/1 not go under the radar for people relying on this image for their backups.

**Comment by adferrand** [comment]
Finally. Next version 4.2.1-1 is released! And so I added a proper changelog.

I close the issue, do not hesitate to reopen if something is missing.
