### ISSUE TITLE
Unrecognized totals option with BusyBox tar

### ISSUE THREAD

**Issue by pandvan** [adferrand/docker-backuppc#28]
We're trying to use _localhost_ backups with _tar_ using the method suggested in the [official FAQ](http://backuppc.sourceforge.net/faq/localhost.html)
Doing so using `$Conf{TarClientCmd} = '$tarPath -c -v -f - -C $shareName+ --totals';` _sudo_ is not needed as it is run inside the container, doesn't work because Alpine uses _tar_ from _BusyBox_ by default, resulting in the following error:
```
/bin/tar: unrecognized option: totals
````
Alpine has also the possibility to install GNU tar from its [repositories](https://pkgs.alpinelinux.org/package/edge/main/x86/tar) that should support also _--totals_ option.
Could be possible to add GNU tar in the runtime dependencies?
https://github.com/adferrand/docker-backuppc/blob/42423ac44ed01e4b43039bb11adb6ddd7f738947/Dockerfile#L11

Many thanks.

**Comment by adferrand** [comment]
Hello @pandvan. I am really sorry for the delay.

I added GNU tar with version 4.3.2-3.
