### ISSUE TITLE
Circusd 100% cpu usage on 75a2cc381f39  4.3.2

### ISSUE THREAD

**Issue by thekoma** [adferrand/docker-backuppc#29]
Hi!
Looks like circus in build 
```

IMAGE
4.3.2
docker pull adferrand/backuppc:4.3.2
Last updated17 hours agobyadferrand
DIGEST
OS/ARCH
COMPRESSED SIZE
75a2cc381f39
linux/amd64
77.84 MB
```
Is eating 100% cpu without apparent reason, backuppc works as usually. 

I've tried to debug it but I had no luck

Fell back in 4.3.1-1 and everything looks fine.

**Comment by adferrand** [comment]
Thanks a lot! I will investigate then.

**Comment by thekoma** [comment]
Thank you for your build!

**Comment by gregbert42** [comment]
Hi - I have the same problem. uses 100% CPU, of one of my virtual CPUs, despite not doing anything apparent. circusd. so glad i found that I am not the first!
            "BACKUPPC_VERSION=4.3.2",
            "BACKUPPC_XS_VERSION=0.59",
            "RSYNC_BPC_VERSION=3.1.2.1",
            "PAR2_VERSION=v0.8.1"

**Comment by adferrand** [comment]
Alright. It seems that circusd 0.16.x is behaving badly on Alpine. I fallbacked to circusd 0.15.0 and it fixed the issue.

New version 4.3.2-1 is building with this fix.

For the long term, I will move to Ubuntu 18.04 and Supervisord, that are more maintained and more used, to avoid this kind of unexpected behavior.

**Comment by thekoma** [comment]
> Alright. It seems that circusd 0.16.x is behaving badly on Alpine. I fallbacked to circusd 0.15.0 and it fixed the issue.
> 
> New version 4.3.2-1 is building with this fix.
> 
> For the long term, I will move to Ubuntu 18.04 and Supervisord, that are more maintained and more used, to avoid this kind of unexpected behavior.

Look out at dumb-init if you like something "KISS" for the init.

**Comment by adferrand** [comment]
I appreciate dumb-init, but it this situation I need more than one process to handle the service represented by this Docker. So I need a proper process manager suitable for containers, like circus and supervisor are.

**Comment by mamema** [comment]
in 4.3.2-1 i get the infamous ln: /bin/bzip2: File exists in the log.

**Comment by adferrand** [comment]
> 
> 
> in 4.3.2-1 i get the infamous ln: /bin/bzip2: File exists in the log.

Could you retry with 4.3.2-2 ?

**Comment by mamema** [comment]
4.3.2-2 isn't available, i've tried 4.3.2-4 and 4.3.2-3 with no success:
ln: /bin/bzip2: File exists
and before that with the first run i got:
 tar: BackupPC-4.3.2-3.tar.gz: Cannot open: No such file or directory

**Comment by mamema** [comment]
My problem is solved since yesterday. After watchtower triggered a update to latest release, all is back to normal operation.

**Comment by thekoma** [comment]
I mark this as closed as the new release solved the problem.
