### ISSUE TITLE
Trying to get circusctl to work as kube *nessprobe

### ISSUE THREAD

**Issue by ambis** [adferrand/docker-backuppc#30]
When I exec as root into backuppc 4.3.2-1, I would assume I could talk to circusd using `circusctl --endpoint ipc:///var/circus/endpoint list` but it times out. 

Any help on how to run `circusctl` inside the container? Since there are no http endpoints that don't require auth in BPC, I'm trying to find something to exec as a readiness/livelynessprobe in kubernetes.

**Comment by adferrand** [comment]
Hello @ambis !

I was planning to move back to supervisord instead of circusd, and I just did in version 4.3.2-2. So you can now use `supervisorctl` to build your readiness probe: I checked, and it is running correctly.

**Comment by ambis** [comment]
Thank you @adferrand ! `supervisorctl status` works like a charm! 🚀
