### ISSUE TITLE
docker-backuppc is not starting after upgrade to latest version

### ISSUE THREAD

**Issue by GiT-BeDa** [adferrand/docker-backuppc#31]
I upgraded to the latest version of docker-backuppc, pulled the latest version and try to run it with Data persistency enabled.

########
First run of the container. BackupPC will be installed.,
If exist, configuration and data will be reused and upgraded as needed.,
tar: BackupPC-4.3.1.tar.gz: Cannot open: No such file or directory,
tar: Error is not recoverable: exiting now,
First run of the container. BackupPC will be installed.,
If exist, configuration and data will be reused and upgraded as needed.,
ln: /bin/bzip2: File exists,
First run of the container. BackupPC will be installed.,
If exist, configuration and data will be reused and upgraded as needed.,
ln: /bin/bzip2: File exists,
########

Do you have any suggestions to fix this?

**Comment by D-sha** [comment]
I also had this problem but it somehow went away, I tried many things and not sure how i solved it - I'm sorry I am aware this is not very helpful!

I think I was able to get it to start removing -d and adding -it to docker run command killing the container and manually starting or killing, removing and pruning all containers and images related to backuppc and restarting.
Hope this is useful somehow!

**Comment by svierne** [comment]
Same problem. :(

**Comment by svierne** [comment]
No idea why, but completely wiping everything except the docker volumes fixed it.

**Comment by csibbitt** [comment]
I believe I am also running into this same problem with 4.4.0. The docker container actually runs just fine the first time, but if I restart it, I get the following:

```
2020-08-05 17:36:17,058 INFO stopped: backuppc (exit status 0)
First run of the container. BackupPC will be installed.
If exist, configuration and data will be reused and upgraded as needed.
usermod: no changes
tar: BackupPC-4.4.0.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting no
```

Removing the container and starting it up again for the "first time" gets it running, with all data and config from my volumes intact.

**Comment by tadr0** [comment]
To me, it looks like there is a misplaced double quote in entrypoint.sh
ie
rm -rf "/root/BackupPC-$BACKUPPC_VERSION.tar.gz" "/root/BackupPC-$BACKUPPC_VERSION /firstrun"
should be
rm -rf "/root/BackupPC-$BACKUPPC_VERSION.tar.gz" "/root/BackupPC-$BACKUPPC_VERSION" /firstrun
this would make sure that /firstrun gets removed

**Comment by adferrand** [comment]
I juste deployed version `4.4.0-2` with the fix for this issue. Really sorry for the mistake...
