### ISSUE TITLE
Invalid MIME types on .css and .js files

### ISSUE THREAD

**Issue by vb4life** [adferrand/docker-backuppc#4]
The MIME types for .gif, .js and .css files are missing from files/lighttpd.conf, causing errors.

`mimetype.assign         = ( ".html" => "text/html", ".txt" => "text/plain", ".jpg" => "image/jpeg", ".png" => "image/png", "" => "application/octet-stream" )`

should be 

`mimetype.assign         = ( ".html" => "text/html", ".txt" => "text/plain", ".jpg" => "image/jpeg", ".png" => "image/png", ".gif" => "image/gif", ".css" => "text/css", ".js" => "text/javascript", "" => "application/octet-stream" )`

**Comment by adferrand** [comment]
Thanks for your report.
I deployed the version 4.1.3-7 of the docker to include the updated MIME types.

Regards,
Adrien Ferrand
