### ISSUE TITLE
LDAP Filter not set correctly

### ISSUE THREAD

**Issue by wrightsonm** [adferrand/docker-backuppc#47]
I don't think the initialisation script is setting the ldap filter correctly.

Observed setting:
/home/backuppc # cat /etc/lighttpd/auth-ldap.conf |grep ldap.filter
auth.backend.ldap.filter                = "(LDAP_FILTER(objectClass=user)(sAMAccountName=$))"

Docker environment value setting:
LDAP_FILTER
(&(objectClass=user)(sAMAccountName=$))

**Comment by AngusMcGyver** [comment]
I had the same problem. The **&** in the filter is a special character in **sed**, which is used in the entrypoint script to fill the template file.

As a quick workaround you can escape it as followed:
`LDAP_FILTER=(\&(objectClass=user)(sAMAccountName=$))`

**Comment by adferrand** [comment]
This is fixed with `4.4.0-7`.
