### ISSUE TITLE
Allow use of local SSL certificate

### ISSUE THREAD

**Issue by higuita** [adferrand/docker-backuppc#5]
I have read the README and looked to the code about the SSL and the solution is easy, add this extra `if` check

```
if [ "$USE_SSL" = true ]; then
+  # Do not generate a certificate if user already mapped the file with docker --volume
+  if [ ! -e /etc/lighttpd/server.pem ]; then
    (...)
+  fi
   # Reconfigure lighttpd to use ssl
```

This way you allow one user to map a certificate file in the host to /etc/lighttpd/server.pem using the docker `--volume` option

`--volume /etc/ssl/private/my-cert.pem:/etc/lighttpd/server.pem`

**Comment by adferrand** [comment]
I saw your proposition and it slipped by mind ... I just made a new version that integrates it: 4.3.0-1.

Thanks a lot !
