### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by michaelschefczyk** [adferrand/docker-backuppc#61]
If I am not mistaken, the current state of the repo leads to a docker build failing with:

Executing busybox-1.33.1-r2.trigger
OK: 425 MiB in 229 packages
Cloning into '/root/backuppc-xs'...
Note: switching to 'b88cc0cabc5f69c82f1bc7eff4fdbb5c4ed8f8dc'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Checking if your kit is complete...
Warning: the following files are missing in your kit:
        META.json
        META.yml
Please inform the author.
Writing MYMETA.yml and MYMETA.json
Writing MYMETA.yml and MYMETA.json
Generating a Unix-style Makefile
Writing Makefile for BackupPC::XS
Writing MYMETA.yml and MYMETA.json
make: /bin/sh: Operation not permitted
make: *** [Makefile:421: blib/lib/BackupPC/.exists] Error 127
The command '/bin/sh -c apk --no-cache --update add         rsync tar bash shadow ca-certificates         supervisor         perl perl-archive-zip perl-xml-rss perl-cgi perl-file-listing perl-json-xs         expat samba-client iputils openssh openssl rrdtool ttf-dejavu         msmtp lighttpd lighttpd-mod_auth gzip apache2-utils tzdata libstdc++ libgomp  && apk --no-cache --update -X http://dl-cdn.alpinelinux.org/alpine/edge/community add par2cmdline  && apk --no-cache --update --virtual build-dependencies add         gcc g++ autoconf automake make git perl-dev acl-dev curl  && git clone https://github.com/backuppc/backuppc-xs.git /root/backuppc-xs --branch $BACKUPPC_XS_VERSION  && cd /root/backuppc-xs  && perl Makefile.PL && make && make test && make install  && git clone https://github.com/backuppc/rsync-bpc.git /root/rsync-bpc --branch $RSYNC_BPC_VERSION  && cd /root/rsync-bpc && ./configure && make reconfigure && make && make install  && rm -f /usr/sbin/sendmail  && ln -s /usr/bin/msmtp /usr/sbin/sendmail  && sed -i -e 's/^# Host \*/Host */g' /etc/ssh/ssh_config  && sed -i -e 's/^#   StrictHostKeyChecking ask/    StrictHostKeyChecking no/g' /etc/ssh/ssh_config  && curl -o /root/BackupPC-$BACKUPPC_VERSION.tar.gz -L https://github.com/backuppc/backuppc/releases/download/$BACKUPPC_VERSION/BackupPC-$BACKUPPC_VERSION.tar.gz  && mkdir -p /home/backuppc && cd /home/backuppc  && touch /firstrun  && rm -rf /root/backuppc-xs /root/rsync-bpc /root/par2cmdline  && apk del build-dependencies' returned a non-zero code: 2

**Comment by adferrand** [comment]
It seems so, something must have changed in the alpine base image. I will look at it tomorrow, thanks for the notice !

**Comment by adferrand** [comment]
Normally everything has been fixed with the previous release in october. Do not hesitate to reopen if there is still an issue.
