### ISSUE TITLE
Not a bug.... I built this for ARM64 and it just worked!

### ISSUE THREAD

**Issue by electricbrain-code** [adferrand/docker-backuppc#62]
I've just finished building on a Raspberry Pi4 8GB running Ubuntu Server.
It just upped and compiled and produced an image!
I'm just testing now and over the next few days.
My 2T BackupPC disk died in the AMD Ryzen 3700X computer and rather than risk Covid-19 and go to the shop, I though I'd just build this container for ARM64 then use the 3T drives on the Pi.
So far so good.
The long and the short of it is: I believe there is scope for a multi-architecture image on hub.docker.com.
Cheers

**Comment by adferrand** [comment]
Thanks a lot, I will give it a try then !

**Comment by electricbrain-code** [comment]
Further to my recent post regarding the success with compiling and creating an ARM64 image (pretty much with zero modifications), I can report that the container is running in Docker Swarm under Portainer control.
Furthermore I recovered enough data from the defunct disk drive to simply use the very same settings and configuration!
Amazingly it is completely functional backing the same computers the Ryzen machine was doing!
Very very happy indeed.
Cheers.

**Comment by adferrand** [comment]
Ok, I set up the multiarch build. The version 4.4.0-8 supports amd64, arm64 and armv7.

**Comment by electricbrain-code** [comment]
Thankyou so much. I shall replace my spin with this one and test it out. My spin has been working very well so I would not expect any issues at all. I will only post again if there is a problem.

Thanks again
eBrain
