### ISSUE TITLE
Build doesn't work, fetched wrong source file for BackupPC 4.4.0

### ISSUE THREAD

**Issue by blomsoft** [adferrand/docker-backuppc#67]
Hi, thanks for making this container! Unfortunately, the build doesn't work anymore, it seems to fetch the wrong release file for Backup PC 4.4.0. It fetches `https://github.com/backuppc/backuppc/archive/$BACKUPPC_VERSION.tar.gz` and this doesn't work, however for me it works with `https://github.com/backuppc/backuppc/releases/download/$BACKUPPC_VERSION/BackupPC-$BACKUPPC_VERSION.tar.gz`.

Kind regards,

Marco

**Comment by adferrand** [comment]
Indeed, I noticed that also. I fixed the URL in the dockerfile, a new release is on its way with the correct one.
