### ISSUE TITLE
Quota exceeded (122) / rsync error: error in file IO (code 11) at receiver.c(391)

### ISSUE THREAD

**Issue by lippoliv** [adferrand/docker-backuppc#7]
Hi there,
I did ran an online-Server with an normal BackupPC. Now I switched to my Synology DS918+ and your very nice Docker Image (thanks for that), because I have Fiber in my office.

Now, backuping the same hosts as I did online, I ran into an Xfer Problem:

```log
[...]
rsync_bpc: write failed on "/gitlab/gitlab/backups/1538954530_2018_10_08_10.7.2_gitlab_backup.tar": Quota exceeded (122)
Done: 0 errors, 0 filesExist, 0 sizeExist, 0 sizeExistComp, 0 filesTotal, 0 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 39877 inode
rsync error: error in file IO (code 11) at receiver.c(391) [receiver=3.0.9.12]
rsync_bpc: connection unexpectedly closed (87 bytes received so far) [generator]
DoneGen: 0 errors, 0 filesExist, 0 sizeExist, 0 sizeExistComp, 1023 filesTotal, 203716527 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 39874 inode
rsync error: error in rsync protocol data stream (code 12) at io.c(629) [generator=3.0.9.12]
rsync_bpc exited with fatal status 12 (3072) (rsync error: error in rsync protocol data stream (code 12) at io.c(629) [generator=3.0.9.12])
           recv >f+++++++++ rw-------     1000,    1000 21513093120 gitlab/gitlab/backups/1538954530_2018_10_08_10.7.2_gitlab_backup.tar
[...]
```
This file is an 21G tar on another host I have a 42G tar, is there any configuration or something else I can set to allow backup of files with 200G?

Disclaimer: I'm not 100% sure if this is a Problem of the Docker Container. I think asking here is a good startpoint to get some Information if someone have similar Problems or do successfull backup such big files.

I appreciate any Information.

**Comment by lippoliv** [comment]
Forget about this one.

I tested a feature of the Synology NAS which is to Limit the size of an Folder. I tested it with the backuppc folder, but I forgot it. And it did what it should do. So actually, the Volume was not full but the feature disallowed to add new files.

I removed this limit and all works well :)

**Comment by adferrand** [comment]
OK, I'm glad that everything is working for you ^^
